name: learned_tri_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - igl=0.4.1
  - intel-openmp=2020.2
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libstdcxx-ng=9.1.0
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.6.12
  - python_abi=3.6
  - readline=8.0
  - scipy=1.5.2
  - setuptools=50.3.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.10.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - grpcio==1.33.1
    - idna==2.10
    - importlib-metadata==2.0.0
    - joblib==0.17.0
    - markdown==3.3.3
    - meshio==4.3.1
    - oauthlib==3.1.0
    - pillow==8.0.1
    - plyfile==0.7.2
    - polyscope==0.1.3
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scikit-learn==0.23.2
    - sklearn==0.0
    - tensorboard==2.1.0
    - threadpoolctl==2.1.0
    - torch==1.4.0
    - torch-cluster==1.4.5
    - torch-scatter==2.0.4
    - torchvision==0.5.0
    - urllib3==1.25.11
    - werkzeug==1.0.1
    - zipp==3.4.0
